### ISSUE TITLE
Full Source Code of your IntelFix

### ISSUE THREAD

**Issue by gilanghamidy** [LazyDuchess/IntelFix#1]
Can you disclose the full source code of the this Intel Fix, and perhaps give an explanation of why Sims 3 application may need this fix? The `dllmain.cpp` and the rest of the project file, but the binary one that you provided in the patcher has some implementation, which roughly:

```
DWORD_PTR gProcAffinity;
DWORD_PTR gSysAffinity;
HANDLE hProc ;

BOOL DllMain(HINSTANCE hInst, DWORD fwdReason, ...)
{
    switch(fwdReason)
    {
    case DLL_PROCESS_ATTACH:
        hProc = GetCurrentProcess();
        GetProcessAffinityMask(hProc, &gProcAffinity, &gSysAffinity);
        SetProcessAffinityMask(hProc, 1);
        CreateThread(NULL, 0, ThreadFunc, hInst, 0, NULL);
    default:
        break;
    }
    return TRUE;
}

DWORD ThreadFunc(LPVOID lpThreadParam)
{
    Sleep(5000);
    SetProcessAffinityMask(hProc, gProcAffinity);
    FreeLibraryAndExitThread(lpThreadParam, 0);
}
```

Is this basically forcing the game to use single core only for the first 5 second, until it reaches the next sequence? Is this related to the DRM problem of several old games that is affected by Alder Lake caused by E-Core? Intel said that the problem has been fixed, but is it actually fixed as well for The Sims, or we will need this implementation onwards?

Thanks for your patch anyway, I am just figuring out what is the reason behind the game not running in Alder Lake (as I am actually planning to buy a new PC :) )

**Comment by LazyDuchess** [comment]
Thank you for the heads up - it does seem like the code didn't get pushed for whatever reason.

It is related to the E-Core issue, I believe the CPUID x86 asm instruction returns non-standard values on E-Cores. The DRM tries to do math with these values, but the different numbers returned by the E-Cores cause a divide by zero, hence the crash. This single core for 5 seconds workaround was the most straightforward way to solve the issue.

I can't really test if it's been fixed myself as I have made this patch based on community feedback, I don't own the appropriate hardware. But if Intel says it's been fixed then I guess it shouldn't be necessary anymore?

**Comment by gilanghamidy** [comment]
Ah I see. I saw some people are still reporting to this bug on the forum or Reddit. But yeah I am planning to buy one myself ASAP, yet a little bit wary since people are reporting some incompatibilities on The Sims 3, which will definitely a total bummer if my new PC cannot even play it lol. But I am quite curious with some of your patch, including this one, that you hook your code into their executable, so I am just ensuring also the security and validity of the patch 😆 _sorry for my extremely paranoid behavior_

Once again, thank you for figuring out. I am also curious, is there any reference regarding this issue anywhere legitimately? Or perhaps since it involves DRM, the knowledge behind this are in the grey zone of the internet? 😄

**Comment by LazyDuchess** [comment]
No problem! I get that one can be paranoid about these things especially when they tend to trip up AVs, that's why it's open source.

I don't really have any documentation at hand about the Alder Lake issue, and I'm not really sure what you mean by legitimate, but I do remember hearing that CPUID was the issue, and I confirmed it myself when checking the exception log. It indeed crashes on a division done by a return value of the instruction.

**Comment by gilanghamidy** [comment]
Ahh I see. I mean, the legitimate source is that the info was not from some shady hacking site that typically has quite deep knowledge about DRM lol 😛 And I think this kind of workaround does not necessarily trip any AV heuristics since it does not do something funny, like maliciously hooking into syscall, shady packer or virtual-machine algorithm, or anti-debugging code that is typically present in malware. That's why I disassemble the binary and look at its implementation to recognize what it does (including your smooth patch) 😁 

Thanks again!

**Comment by gilanghamidy** [comment]
Oh anw, I am going to build a new Alder Lake PC tomorrow, so I'll see if Sims 3 can run without this patch, otherwise I'll use your patch. :grin:

**Comment by gilanghamidy** [comment]
Just a heads-up, the problem indeed persists without the patch. But using the patch, it works. So I guess the developer must patch on their own for this new CPUID behavior that they use for the DRM. Let's see if EA actually does something with it

**Comment by LazyDuchess** [comment]
Oh well, good to know the patch is working for you at least. I wouldn't hold my breath for an official fix coming anytime soon knowing EA.
